import type { Metadata } from "next";
import { Inter} from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { TRPCReactProvider } from "@/trpc/client";
import {NuqsAdapter} from "nuqs/adapters/next";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "meet ai",
  description: "Generated by create next app",
  icons : {
    icon : "/logo.png",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NuqsAdapter>
    <TRPCReactProvider>
      <html lang="en">
        <body
          className={` ${inter.className} antialiased`}
        >
          <Toaster
            position="bottom-right"
          />
          {children}
        </body>
      </html>
    </TRPCReactProvider>
    </NuqsAdapter>
  );
}
